#include "QCartesianGeometry.h"
#include<QObject>

// ===== Cartesian =====
QPointF QCartesianGeometry::mapToPixel(qreal x, qreal y)const { QRectF a = plotArea();qreal px = a.left(), py = a.bottom();if (m_axisX)px += m_axisX->mapToPixel(x, a.width());if (m_axisY)py -= m_axisY->mapToPixel(y, a.height());return{ px,py }; }
QPointF QCartesianGeometry::mapFromPixel(const QPointF& p)const { QRectF a = plotArea();qreal x = 0, y = 0;if (m_axisX)x = m_axisX->pixelToValue(p.x() - a.left(), a.width());if (m_axisY)y = m_axisY->pixelToValue(a.bottom() - p.y(), a.height());return{ x,y }; }
void QCartesianGeometry::drawGrid(QPainter* p) { if (!m_gridVisible)return;p->save();QRectF a = plotArea();qreal w = a.width(), h = a.height();p->setPen(QPen(m_gridColor, 1, Qt::DashLine));auto draw = [&](QChartAxis* ax, bool vert) {if (!ax)return;for (qreal t : ax->tickValues()) { qreal pos = ax->mapToPixel(t, vert ? h : w);if (vert) { qreal y = a.bottom() - pos;p->drawLine(QPointF(a.left(), y), QPointF(a.right(), y)); } else { qreal x = a.left() + pos;p->drawLine(QPointF(x, a.top()), QPointF(x, a.bottom())); } }};draw(m_axisY, true);draw(m_axisX, false);p->restore(); }

void QCartesianGeometry::drawSeries(QPainter* p, QAbstractSeries* s) { if (auto* ls = qobject_cast<QLineSeries*>(s)) { drawLineSeries(p, ls);return; }if (auto* ss = qobject_cast<QScatterSeries*>(s)) { drawScatterSeries(p, ss);return; }if (auto* bs = qobject_cast<QBarSeries*>(s)) { drawBarSeries(p, bs);return; } }
int QCartesianGeometry::hitTestSeries(QAbstractSeries* s, const QPointF& pos)const { if (auto* ls = qobject_cast<QLineSeries*>(s)) { qreal md = 12;int best = -1;for (int i = 0;i < ls->count();++i) { auto d = mapToPixel(ls->points()[i].x(), ls->points()[i].y());if (std::hypot(d.x() - pos.x(), d.y() - pos.y()) < md)best = i; }return best; }if (auto* ss = qobject_cast<QScatterSeries*>(s)) { qreal md = ss->markerSize() * 2;for (int i = ss->count() - 1;i >= 0;--i) { auto d = mapToPixel(ss->points()[i].x(), ss->points()[i].y());if (std::hypot(d.x() - pos.x(), d.y() - pos.y()) < md)return i; } }return -1; }

static void drawSmoothPath(QPainter* p, const QVector<QPointF>& pts) { int n = pts.size();if (n < 2)return;if (n == 2) { p->drawLine(pts[0], pts[1]);return; }QPainterPath path;path.moveTo(pts[0]);for (int i = 0;i < n - 1;++i) { QPointF p0 = (i > 0) ? pts[i - 1] : pts[i], p1 = pts[i], p2 = pts[i + 1], p3 = (i < n - 2) ? pts[i + 2] : pts[i + 1];path.cubicTo(p1 + (p2 - p0) / 6., p2 - (p3 - p1) / 6., p2); }p->drawPath(path); }
static void drawMarker(QPainter* p, const QPointF& c, qreal sz, QScatterSeries::MarkerShape sh, const QColor& f, const QColor& b) { QPainterPath pp;qreal r = sz / 2;switch (sh) { case QScatterSeries::Circle:pp.addEllipse(c, r, r);break;case QScatterSeries::Rectangle:pp.addRect(c.x() - r, c.y() - r, sz, sz);break;case QScatterSeries::Triangle:pp.moveTo(c.x(), c.y() - r);pp.lineTo(c.x() + r, c.y() + r);pp.lineTo(c.x() - r, c.y() + r);pp.closeSubpath();break;case QScatterSeries::Diamond:pp.moveTo(c.x(), c.y() - r);pp.lineTo(c.x() + r, c.y());pp.lineTo(c.x(), c.y() + r);pp.lineTo(c.x() - r, c.y());pp.closeSubpath();break;case QScatterSeries::Star: { qreal oR = r, iR = r * .4;for (int i = 0;i < 10;++i) { qreal a = -M_PI / 2 + i * M_PI / 5;qreal rr = (i % 2 == 0) ? oR : iR;QPointF pt(c.x() + rr * cos(a), c.y() + rr * sin(a));if (i == 0)pp.moveTo(pt);else pp.lineTo(pt); }pp.closeSubpath();break; }case QScatterSeries::Cross:pp.moveTo(c.x() - r * .6, c.y() - r);pp.lineTo(c.x() + r * .6, c.y() + r);pp.moveTo(c.x() + r * .6, c.y() - r);pp.lineTo(c.x() - r * .6, c.y() + r);break; }p->setPen(QPen(b, 1));p->setBrush(f);p->drawPath(pp); }

																																																			  void QCartesianGeometry::drawLineSeries(QPainter* p, QLineSeries* ls) { auto& pts = ls->points();if (pts.size() < 2)return;QVector<QPointF> sp;sp.reserve(pts.size());for (auto& pt : pts)sp.append(mapToPixel(pt.x(), pt.y()));p->setPen(QPen(ls->color(), ls->lineWidth(), Qt::SolidLine, Qt::RoundCap, Qt::RoundJoin));p->setBrush(Qt::NoBrush);if (ls->smooth())drawSmoothPath(p, sp);else { QPainterPath ph;ph.moveTo(sp[0]);for (int i = 1;i < sp.size();++i)ph.lineTo(sp[i]);p->drawPath(ph); }if (ls->pointsVisible()) { QColor bd = ls->color().darker(140);p->setPen(QPen(bd, 1));p->setBrush(ls->color());for (auto& pt : sp)p->drawEllipse(pt, ls->pointSize() / 2, ls->pointSize() / 2); } }
																																																			  void QCartesianGeometry::drawScatterSeries(QPainter* p, QScatterSeries* ss) { QColor bd = ss->color().darker(140);for (auto& pt : ss->points()) { QPointF sp = mapToPixel(pt.x(), pt.y());drawMarker(p, sp, ss->markerSize(), ss->markerShape(), ss->color(), bd); } }
																																																			  void QCartesianGeometry::drawBarSeries(QPainter* p, QBarSeries* bs) { auto cats = bs->categories();auto sets = bs->barSets();if (cats.isEmpty() || sets.isEmpty())return;int nC = cats.size(), nS = sets.size();bool horiz = (bs->orientation() == QBarSeries::Horizontal);QRectF a = plotArea();qreal catLen = horiz ? a.height() : a.width(), valLen = horiz ? a.width() : a.height();qreal slotW = catLen / nC;QVector<qreal> sB(nC, 0), sT(nC, 0);if (bs->barsType() != QBarSeries::Groups)for (int c = 0;c < nC;++c) { qreal t = 0;for (auto* st : sets)t += st->valueAt(c);sT[c] = t; }p->save();for (int si = 0;si < nS;++si) { auto* st = sets[si];for (int ci = 0;ci < nC;++ci) { qreal rv = st->valueAt(ci);if (rv <= 0 && bs->barsType() != QBarSeries::StackedPercent)continue;qreal val = rv, base = 0;if (bs->barsType() == QBarSeries::Stacked) { base = sB[ci];sB[ci] += val; } else if (bs->barsType() == QBarSeries::StackedPercent) { qreal t = sT[ci];if (t <= 0)continue;base = sB[ci];val = rv / t * 100.;sB[ci] += val; }QRectF bar;if (horiz) { qreal yB = a.bottom() - ci * slotW;qreal gH = slotW * bs->barWidth();qreal bH = gH / nS;qreal y = yB - (slotW - gH) / 2 - si * bH;qreal xL = a.left() + m_axisX->mapToPixel(base, valLen);qreal xR = a.left() + m_axisX->mapToPixel(base + val, valLen);bar = QRectF(qMin(xL, xR), y - bH, qAbs(xR - xL), bH); } else { qreal xB = a.left() + ci * slotW;qreal gW = slotW * bs->barWidth();qreal bW = gW / nS;qreal x = xB + (slotW - gW) / 2 + si * bW;qreal yB = a.bottom() - m_axisY->mapToPixel(base, valLen);qreal yT = a.bottom() - m_axisY->mapToPixel(base + val, valLen);bar = QRectF(x, qMin(yT, yB), bW, qAbs(yT - yB)); }QColor c = st->color().isValid() ? st->color() : bs->color();if (bs->barRadius() > 0) { QPainterPath pp;pp.addRoundedRect(bar, bs->barRadius(), bs->barRadius());p->fillPath(pp, c); } else p->fillRect(bar, c); } }p->restore(); }
