#include "QPolarGeometry.h"

// ===== Polar =====
QPolarGeometry::QPolarGeometry(QObject* p) :QChartGeometry(p) {}
void QPolarGeometry::autoFit() { QRectF a = plotArea();qreal sz = qMin(a.width(), a.height());/* auto-fit just ensures plotArea is set; axis ranges define the mapping */ }
QPointF QPolarGeometry::mapToPixel(qreal angleDeg, qreal rNorm)const { QRectF a = plotArea();QPointF c = a.center();qreal maxR = qMin(a.width(), a.height()) / 2;qreal innerR = maxR * (m_axisY ? m_axisY->min() : 0);qreal r = innerR + rNorm * (maxR - innerR);qreal rad = qDegreesToRadians(angleDeg - 90);return{ c.x() + r * qCos(rad),c.y() - r * qSin(rad) }; }
QPointF QPolarGeometry::mapFromPixel(const QPointF& p)const { QRectF a = plotArea();QPointF c = a.center();qreal dx = p.x() - c.x(), dy = p.y() - c.y();qreal d = std::hypot(dx, dy);qreal deg = qRadiansToDegrees(qAtan2(-dy, dx)) + 90;if (deg < 0)deg += 360;qreal maxR = qMin(a.width(), a.height()) / 2;qreal innerR = maxR * (m_axisY ? m_axisY->min() : 0);qreal n = (d - innerR) / (maxR - innerR);return{ deg,qBound(0.,n,1.) }; }
void QPolarGeometry::drawGrid(QPainter* p) { if (!m_gridVisible)return;p->save();QRectF a = plotArea();QPointF c = a.center();qreal maxR = qMin(a.width(), a.height()) / 2;qreal innerR = maxR * (m_axisY ? m_axisY->min() : 0);p->setPen(QPen(m_gridColor, 1, Qt::DotLine));for (int i = 1;i <= 4;++i) { qreal r = innerR + (maxR - innerR) * i / 4.;p->drawEllipse(c, r, r); }p->setPen(QPen(Qt::black, 1));p->drawLine(QPointF(c.x(), a.top()), QPointF(c.x(), a.bottom()));p->drawLine(QPointF(a.left(), c.y()), QPointF(a.right(), c.y()));p->restore(); }
void QPolarGeometry::drawSeries(QPainter* p, QAbstractSeries* s) { if (auto* ps = qobject_cast<QPieSeries*>(s))drawPieSeries(p, ps); }
int QPolarGeometry::hitTestSeries(QAbstractSeries* s, const QPointF& pos)const { if (auto* ps = qobject_cast<QPieSeries*>(s)) { QPointF dp = mapFromPixel(pos);return ps->sliceAtAngle(dp.x(), dp.y()); }return -1; }

void QPolarGeometry::drawPieSeries(QPainter* p, QPieSeries* ps) { if (ps->sliceCount() == 0)return;qreal total = ps->totalValue();if (total <= 0)return;QRectF a = plotArea();QPointF center = a.center();qreal maxR = qMin(a.width(), a.height()) / 2;qreal innerR = maxR * (m_axisY ? m_axisY->min() : 0);qreal startAngle = m_axisX ? m_axisX->min() : 90;qreal curA = startAngle - 90;for (int i = 0;i < ps->sliceCount();++i) { auto& sl = ps->sliceAt(i);qreal span = sl.value / total * 360.;if (span <= 0)continue;qreal off = sl.explodeOffset * maxR * sl.explodeFactor;qreal midA = qDegreesToRadians(curA + span / 2);QPointF co = center + QPointF(off * qCos(midA), -off * qSin(midA));QPointF os = mapToPixel(curA, 1.) + (co - center), oe = mapToPixel(curA + span, 1.) + (co - center);QPointF is = mapToPixel(curA, 0.) + (co - center), ie = mapToPixel(curA + span, 0.) + (co - center);QPainterPath path;path.moveTo(os);path.arcTo(QRectF(co.x() - maxR, co.y() - maxR, maxR * 2, maxR * 2), curA, span);if (innerR > 0) { path.lineTo(ie);path.arcTo(QRectF(co.x() - innerR, co.y() - innerR, innerR * 2, innerR * 2), curA + span, -span); }path.closeSubpath();p->fillPath(path, sl.color);if (!sl.label.isEmpty()) { qreal la = qDegreesToRadians(curA + span / 2);qreal lr = innerR > 0 ? (innerR + maxR) / 2 : maxR * .6;QPointF lp = co + QPointF(lr * qCos(la), -lr * qSin(la));p->setPen(Qt::white);QFont f = p->font();f.setPointSize(f.pointSize() - 2);p->setFont(f);p->drawText(QRectF(lp.x() - 30, lp.y() - 10, 60, 20), Qt::AlignCenter, sl.label); }curA += span; } }
